services:
  - type: web
    name: app-escolar-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app_escolar_api.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: app-escolar-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

databases:
  - name: app-escolar-db
    databaseName: app_escolar_db
    user: app_escolar_user
